### ISSUE TITLE
Checkstyle errors in Movie, Session and Hall

### ISSUE THREAD

**Issue by Seregy** [Seregy/movie-tickets#1]
All code in this project should be written according to the Checkstyle rules, specified in 'sun_checks.xml'(modified version of http://checkstyle.sourceforge.net/sun_style.html). Please, fix this
![idea_2017-03-19_16-24-11](https://cloud.githubusercontent.com/assets/9089329/24081654/a2010092-0cc0-11e7-861a-7f964049e110.png)

**Comment by CatReeena** [comment]
бебебе
